#!/bin/bash
#rounding tool - interactive mode v2.00
#

#roundm alias setup
#
#
#touch ~/installed_roundm
INSTALLED_ROUNDM=$(<~/installed_roundm)
calc -d "$INSTALLED_ROUNDM + 0" > installed_or_not
INSTALLED_OR_NOT=$(<installed_or_not)

if [[ $INSTALLED_OR_NOT -eq 0 ]]
then

echo "$PWD" > roundm_path
echo "/roundm" >> roundm_path
cat roundm_path | tr -d '\n' > roundm_path2
cp roundm_path2 ~

cd

ROUNDM_PATH=$(<roundm_path2)
echo 'alias ' > alias_roundm
echo "roundm=" >> alias_roundm
echo "'" >> alias_roundm
echo "bash " >> alias_roundm
echo "$ROUNDM_PATH" >> alias_roundm
echo "'" >> alias_roundm
cat alias_roundm | tr -d '\n' > roundm_alias
ALIAS=$(<roundm_alias)

echo "$ALIAS" >> ~/.bashrc 
. ~/.bashrc
echo '1' > installed_roundm

rm alias_roundm roundm_alias roundm_path2

cd -

echo 'roundm is now set up and ready to go!'

else
echo 'V'
rm installed_or_not
fi


#
#
echo 'Enter path to file including full file name'
read FILE_PATH
echo "$FILE_PATH" > file_path.txt
echo ''
echo 'If the following file only contains one numerical value per line'
echo 'where the integer is separated from the decimal(s) by either dot or comma'
echo 'then hit enter, else use ctrl-c'
echo "FILE = $FILE_PATH"
echo ''
read -p '...'
echo 'done'


#
#
echo 'Round up (1) or down (2)?'
read SELECTION_UPDOWN
echo "$SELECTION_UPDOWN" > selection_updown.txt


#
#
echo 'Choose 1 for v1.01 (round with integer as starting point)'
echo 'Choose 2 for v1.02 (round with 0 as starting point)'
read SELECTION_MODULE
echo "$SELECTION_MODULE" > selection_module.txt 


#
#
echo 'Round to nearest (multiple) of what decimal(s)?'
read INPUT_ROUNDING
echo "$INPUT_ROUNDING" > round_to_this.txt



#UP
#
#
#
if [[ $SELECTION_UPDOWN -eq 1 ]] && [[ $SELECTION_MODULE -eq 1 ]]
then
input="$FILE_PATH"
while IFS= read -r line
do
  echo "$line" > full_number_1_dotcom.txt && sed 's/,/./g' full_number_1_dotcom.txt > full_number_1.txt && bash rounding-up-module-v101-for-lists.sh
done < "$input"
fi

if [[ $SELECTION_UPDOWN -eq 1 ]] && [[ $SELECTION_MODULE -eq 2 ]]
then
input="$FILE_PATH"
while IFS= read -r line
do
  echo "$line" > full_number_1_dotcom.txt && sed 's/,/./g' full_number_1_dotcom.txt > full_number_1.txt && bash rounding-up-module-v102-for-lists.sh
done < "$input"
fi



#DOWN
#
#
#
if [[ $SELECTION_UPDOWN -eq 2 ]] && [[ $SELECTION_MODULE -eq 1 ]]
then
input="$FILE_PATH"
while IFS= read -r line
do
  echo "$line" > full_number_1_dotcom.txt && sed 's/,/./g' full_number_1_dotcom.txt > full_number_1.txt && bash rounding-down-module-v101-for-lists.sh
done < "$input"
fi

if [[ $SELECTION_UPDOWN -eq 2 ]] && [[ $SELECTION_MODULE -eq 2 ]]
then
input="$FILE_PATH"
while IFS= read -r line
do
  echo "$line" > full_number_1_dotcom.txt && sed 's/,/./g' full_number_1_dotcom.txt > full_number_1.txt && bash rounding-down-module-v102-for-lists.sh
done < "$input"
fi

read -p 'pause'

#remove temp files
rm file_path.txt full_number_1_dotcom.txt selection_updown.txt


#V
